nome = str(input('Digite seu nome completo:')).strip()
mainome = nome.upper()
minnome = nome.lower()
sepnome = nome.split()
print('Seu nome em maiúsculo é {}'.format(mainome))
print('Seu nome em minúsculo é {}'.format(minnome))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(sepnome[0], len(sepnome[0])))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
